---
- name: Set git user.name
  become_user: "{{ user.name }}"
  git_config:
    name: user.name
    scope: global
    value: "{{ git.user.name }}"

- name: Set git user.email
  become_user: "{{ user.name }}"
  git_config:
    name: user.email
    scope: global
    value: "{{ git.user.email }}"

- name: Set git core.editor
  become_user: "{{ user.name }}"
  git_config:
    name: core.editor
    scope: global
    value: nvim
