---
- hosts: all
  become: yes

  # copy defaults.yml to vars.yml and change variable to your needs
  vars_files:
  - defaults.yml
  - vars.yml

  tasks:
  - name: Display vars
    debug:
      msg: "Provisioning with vars
          user.name: {{user.name}}
          proxy.address: {{proxy.address}}
          proxy.noproxy: {{proxy.noproxy}}"

  - import_tasks: mirrors.yml

  - import_tasks: update.yml

  # problem with guest additions
  #    - import_tasks: lts.yml

  - name: set timezone to Europe/Berlin
    timezone:
      name: Europe/Berlin

  - name: Colorize pacman
    replace:
      path: /etc/pacman.conf
      regexp: ^#Color
      replace: Color

  - import_tasks: users.yml

  - import_tasks: proxy.yml

  - name: Install essentials
    pacman:
      name: htop tmux neovim xdg-utils unzip
      state: present

  - import_tasks: docker.yml

  - name: Check yay
    shell: pacman -Qi yay
    ignore_errors: yes
    failed_when: no
    register: yay_check

  - import_tasks: yay.yml
    when: yay_check.rc != 0

  - name: Install vim-plug
    become: no
    shell: yay -S vim-plug --needed --noconfirm

  - import_tasks: zsh.yml

  - import_tasks: gitcfg.yml

  - import_tasks: guest_additions.yml

  - import_tasks: java_sdkman.yml

  - import_tasks: gnome.yml

  - name: Install graphical
    pacman:
      name: firefox chromium
      state: present

  - name: Install intellij idea
    become: no
    shell: yay -S intellij-idea-ultimate-edition --needed --noconfirm
